### ISSUE TITLE
can't cast [useMuraDefault] to date value 

### ISSUE THREAD

**Issue by tbugler** [meldsolutions/Meld-Google-Sitemaps#46]
Lucee 5.2
Windows IIS 8.5

can't cast [useMuraDefault] to date value 

Code: 0 

Type: expression 

			
				lucee.runtime.exp.ExpressionException: can't cast [useMuraDefault] to date value
	at lucee.runtime.op.date.DateCaster.toDateAdvanced(DateCaster.java:83)
	at lucee.runtime.op.Caster.toDate(Caster.java:2829)
	at lucee.runtime.db.SQLCaster.setValue(SQLCaster.java:329)
	at lucee.runtime.type.QueryImpl.setItems(QueryImpl.java:367)
	at lucee.runtime.type.QueryImpl.execute(QueryImpl.java:274)
	at lucee.runtime.type.QueryImpl.<init>(QueryImpl.java:221)
	at lucee.runtime.tag.Query.executeDatasoure(Query.java:864)
	at lucee.runtime.tag.Query.doEndTag(Query.java:622)
	at extend.extendmanager_cfc$cf.udfCall2(/mura/extend/extendManager.cfc:482)
	at extend.extendmanager_cfc$cf.udfCall(/mura/extend/extendManager.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701)
	at extend.extendobject_cfc$cf.udfCall2(/mura/extend/extendObject.cfc:132)
	at extend.extendobject_cfc$cf.udfCall(/mura/extend/extendObject.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701)
	at process.controllers.main_cfc$cf.udfCall(/MeldGoogleSitemaps/process/controllers/main.cfc:44)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:211)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1931)
	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)
	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)
	at framework_cfc$cf.udfCall6(/MeldGoogleSitemaps/framework.cfc:1247)
	at framework_cfc$cf.udfCall(/MeldGoogleSitemaps/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:772)
	at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:758)
	at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1701)
	at framework_cfc$cf.udfCall2(/MeldGoogleSitemaps/framework.cfc:483)
	at framework_cfc$cf.udfCall(/MeldGoogleSitemaps/framework.cfc)
	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)
	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)
	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)
	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)
	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)
	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:222)
	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)
	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408)
	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398)
	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366)
	at lucee.runtime.engine.Request.run(Request.java:34)

			

Column: 0
ID: ??
Line: 482
Raw Trace: extend.extendmanager_cfc$cf.udfCall2(/mura/extend/extendManager.cfc:482)
Template: E:\wwwroot\requirements\mura\extend\extendManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 132
Raw Trace: extend.extendobject_cfc$cf.udfCall2(/mura/extend/extendObject.cfc:132)
Template: E:\wwwroot\requirements\mura\extend\extendObject.cfc
Type: cfml

Column: 0
ID: ??
Line: 44
Raw Trace: process.controllers.main_cfc$cf.udfCall(/MeldGoogleSitemaps/process/controllers/main.cfc:44)
Template: E:\wwwroot\plugins\MeldGoogleSitemaps\process\controllers\main.cfc
Type: cfml

Column: 0
ID: ??
Line: 1247
Raw Trace: framework_cfc$cf.udfCall6(/MeldGoogleSitemaps/framework.cfc:1247)
Template: E:\wwwroot\plugins\MeldGoogleSitemaps\framework.cfc
Type: cfml

Column: 0
ID: ??
Line: 483
Raw Trace: framework_cfc$cf.udfCall2(/MeldGoogleSitemaps/framework.cfc:483)
Template: E:\wwwroot\plugins\MeldGoogleSitemaps\framework.cfc
Type: cfml

**Comment by tbugler** [comment]
If the Auto Generation isn't enabled and you try to manually create a sitemap you get the above error. Once you enable Auto Generation you can manually generate a sitemap (as well as it be auto generated on a schedule).
