### ISSUE TITLE
MURA  7  occassionally throwing String index out of range: -6

### ISSUE THREAD

**Issue by tbugler** [meldsolutions/Meld-Google-Sitemaps#47]
Running on IIS8 / Lucee 5.1
500 Error
String index out of range: -6
Code:0
Type:java.lang.StringIndexOutOfBoundsException

lucee.runtime.exp.NativeException: String index out of range: -6

	at lucee.runtime.exp.NativeException.newInstance(NativeException.java:73)

	at lucee.runtime.op.Caster.toPageException(Caster.java:3201)

	at lucee.runtime.op.Caster.toPageException(Caster.java:3176)

	at application_cfc$cf.initComponent(/MeldGoogleSitemaps/Application.cfc:193)

	at application_cfc$cf.newInstance(/MeldGoogleSitemaps/Application.cfc:20)

	at lucee.runtime.component.ComponentLoader.initComponent(ComponentLoader.java:543)

	at lucee.runtime.component.ComponentLoader._loadComponent(ComponentLoader.java:480)

	at lucee.runtime.component.ComponentLoader.load(ComponentLoader.java:399)

	at lucee.runtime.component.ComponentLoader._search(ComponentLoader.java:288)

	at lucee.runtime.component.ComponentLoader._search(ComponentLoader.java:100)

	at lucee.runtime.component.ComponentLoader.searchComponent(ComponentLoader.java:74)

	at lucee.runtime.PageContextImpl.loadComponent(PageContextImpl.java:3140)

	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:218)

	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)

	at meldgooglesitemaps.events.eventhandler_cfc$cf.udfCall(/plugins/MeldGoogleSitemaps/events/eventHandler.cfc:34)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:211)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1931)

	at lucee.runtime.tag.Invoke.doComponent(Invoke.java:221)

	at lucee.runtime.tag.Invoke.doEndTag(Invoke.java:194)

	at plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1610)

	at plugin.pluginmanager_cfc$cf.udfCall(/mura/plugin/pluginManager.cfc)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)

	at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:211)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:698)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)

	at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1935)

	at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:835)

	at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1722)

	at config.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/config/appcfc/onApplicationStart_include.cfm:454)

	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:928)

	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:842)

	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:826)

	at config.appcfc.onrequeststart_include_cfm$cf.call(/config/appcfc/onRequestStart_include.cfm:104)

	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:928)

	at lucee.runtime.PageContextImpl._doInclude(PageContextImpl.java:842)

	at lucee.runtime.PageContextImpl.doInclude(PageContextImpl.java:826)

	at admin.application_cfc$cf.udfCall(/admin/Application.cfc:169)

	at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)

	at lucee.runtime.type.UDFImpl._call(UDFImpl.java:338)

	at lucee.runtime.type.UDFImpl.call(UDFImpl.java:225)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:697)

	at lucee.runtime.ComponentImpl._call(ComponentImpl.java:580)

	at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1918)

	at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:420)

	at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:132)

	at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:43)

	at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2408)

	at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2398)

	at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2366)

	at lucee.runtime.engine.Request.run(Request.java:34)

Column: 0
ID: ??
Line: 193
Raw Trace: application_cfc$cf.initComponent(/MeldGoogleSitemaps/Application.cfc:193)
Template: E:\wwwroot\ssw\plugins\MeldGoogleSitemaps\Application.cfc
Type: cfml

Column: 0
ID: ??
Line: 20
Raw Trace: application_cfc$cf.newInstance(/MeldGoogleSitemaps/Application.cfc:20)
Template: E:\wwwroot\ssw\plugins\MeldGoogleSitemaps\Application.cfc
Type: cfml

Column: 0
ID: ??
Line: 34
Raw Trace: meldgooglesitemaps.events.eventhandler_cfc$cf.udfCall(/plugins/MeldGoogleSitemaps/events/eventHandler.cfc:34)
Template: E:\wwwroot\ssw\plugins\MeldGoogleSitemaps\events\eventHandler.cfc
Type: cfml

Column: 0
ID: ??
Line: 1610
Raw Trace: plugin.pluginmanager_cfc$cf.udfCall3(/mura/plugin/pluginManager.cfc:1610)
Template: E:\wwwroot\ssw\requirements\mura\plugin\pluginManager.cfc
Type: cfml

Column: 0
ID: ??
Line: 454
Raw Trace: config.appcfc.onapplicationstart_include_cfm$cf.call(/muraWRM/config/appcfc/onApplicationStart_include.cfm:454)
Template: E:\wwwroot\ssw\config\appcfc\onApplicationStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 104
Raw Trace: config.appcfc.onrequeststart_include_cfm$cf.call(/config/appcfc/onRequestStart_include.cfm:104)
Template: E:\wwwroot\ssw\config\appcfc\onRequestStart_include.cfm
Type: cfml

Column: 0
ID: ??
Line: 169
Raw Trace: admin.application_cfc$cf.udfCall(/admin/Application.cfc:169)
Template: E:\wwwroot\ssw\admin\Application.cfc
Type: cfml

**Comment by IvanRotrekl** [comment]
Looks like this is caused by line 34 in the [pluginDir]events/eventHandler.cfc" 

`<!--- invoke onApplicationStart in the application.cfc so the framework can do its thing---> <cfinvoke component="#pluginConfig.getPackage()#.Application" method="onApplicationStart" />`

the path to the Applicaton.cfc  is missing the plugins dir and should be:
`<cfinvoke component="plugins.#pluginConfig.getPackage()#.Application" method="onApplicationStart" />`

Regards

Ivan
